// Generated by CoffeeScript 1.12.4
var assert, boxes, chai, chalk, exec, fs, prepared, read;

fs = require('fs');

read = function(file) {
  return fs.readFileSync(file).toString();
};

chai = require('chai');

assert = chai.assert;

exec = require('sync-exec');

chalk = require('chalk');

prepared = chalk.keyword('green');

boxes = function(name, n) {
  console.log('STARTED PREPARING TEST "' + name + '"');
  exec('gulp', {
    cwd: 'test/' + n
  });
  console.log(prepared('FINISHED PREPARING TEST "' + name + '"'));
  return it(name, function() {
    var text1, text2;
    text1 = read('test/' + n + '/results/text.txt');
    text2 = read('test/' + n + '/true-result.txt');
    return assert.equal(text1, text2);
  });
};

describe('gulp-boxen', function() {
  boxes('Draw text "GULP-BOXEN"', 1);
  boxes('Draw text "some text"', 2);
  return boxes('Draw empty box', 3);
});
