// Generated by CoffeeScript 1.12.4
var del, exec, gulp, uglify;

gulp = require('gulp');

uglify = require('gulp-uglify');

del = require('del');

exec = require('child_process').exec;

gulp.task('build', function() {
  del('build/index.js');
  gulp.src('index.js').pipe(uglify()).pipe(gulp.dest('build/'));
  return gulp.src('package.json').pipe(gulp.dest('build/'));
});

gulp.task('upload', function() {});