// Generated by CoffeeScript 1.12.4
var del, exec, gulp, mocha, seq, uglify;

gulp = require('gulp');

uglify = require('gulp-uglify');

mocha = require('gulp-mocha');

del = require('del');

seq = require('run-sequence');

exec = require('child_process').exec;

gulp.task('build', function() {
  del('build/index.js');
  gulp.src('index.js').pipe(uglify()).pipe(gulp.dest('build/'));
  return gulp.src('package.json').pipe(gulp.dest('build/'));
});

gulp.task('test', function() {
  return gulp.src('test/test.js').pipe(mocha());
});

gulp.task('default', function() {
  return seq('test', 'build');
});
