// Generated by CoffeeScript 1.12.4
var Duplex, boxen, stream, th, toStream, util;

util = require('gulp-util');

th = require('through2');

stream = require('stream');

boxen = require('boxen');

Duplex = stream.Duplex;

toStream = function(buffer) {
  stream = new Duplex;
  stream.push(buffer);
  stream.push(null);
  return stream;
};

module.exports = function(settings) {
  var end, pipe;
  pipe = function(file, enc, callback) {
    var allText, self;
    if (file.isNull()) {
      return callback(null, file);
    }
    if (file.isBuffer()) {
      file.contents = toStream(file.contents);
    }
    allText = "";
    file.contents = file.contents.pipe(th.obj(function(chunk, enc, callback) {
      allText += chunk.toString();
      return callback(null, chunk);
    }));
    self = this;
    file.contents.on('finish', function() {
      var box;
      box = boxen(allText, settings);
      file.contents = new Buffer(box);
      return self.push(file);
    });
    return callback(null, file);
  };
  end = function(callback) {
    return callback();
  };
  return th.obj(pipe, end);
};
