// Generated by CoffeeScript 1.12.4
var boxen, del, gulp;

gulp = require('gulp');

del = require('del');

boxen = require('../../index.js');

gulp.task('build', function() {
  return gulp.src('text.txt').pipe(boxen({
    padding: 3,
    margin: 2,
    borderStyle: "double"
  })).pipe(gulp.dest('results'));
});

gulp.task('clean', function() {
  return del('results');
});

gulp.task('default', ['build']);
