// Generated by CoffeeScript 1.12.4
var boxen, del, gulp, seq;

gulp = require('gulp');

del = require('del');

seq = require('run-sequence');

boxen = require('../../index.js');

gulp.task('build', function() {
  return gulp.src('text.txt').pipe(boxen({
    padding: 2,
    margin: 1,
    borderStyle: "round"
  })).pipe(gulp.dest('results'));
});

gulp.task('clean', function() {
  return del('results');
});

gulp.task('default', function() {
  return seq('clean', 'build');
});
